# Generated by Django 3.0.3 on 2020-02-10 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20200210_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.Products'),
        ),
    ]
