# Generated by Django 3.0.3 on 2020-02-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200211_0327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
